name: ma_meteo
description:
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  # API
  http: ^1.2.1
  mockito: ^5.4.4
  # Utils
  latlong2: ^0.9.1
  email_validator: '^2.1.16'
  intl: ^0.19.0
  geolocator: ^11.0.0
  flutter_secure_storage: ^9.0.0
  universal_io: ^2.2.2
  # UI
  flutter_svg: ^2.0.10+1
  grouped_list: ^5.1.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/icons/mail.svg
    - assets/icons/logout.svg
    - assets/icons/pass.svg
    - assets/icons/warning.svg
    - assets/icons/marker.svg